### ISSUE TITLE
Timed out waiting for response from LiveOSC. Is Live running and LiveOSC installed?

### ISSUE THREAD

**Issue by laimison** [ideoforms/pylive#27]
Hi,

Anyone has some ideas what to check?

* Ableton 10
* I have python dependencies and LiveOSC installed
* Except I didn't manage to successfully install `liblo`

Reaching this line:

https://github.com/ideoforms/pylive/blob/master/live/query.py#L240

My script:

```
#!/usr/bin/env python3
import live

set = live.Set()
set.scan(scan_devices=True, scan_clip_names=True) # this line fails
set.master_volume = 0
```

My error:

```
$ ~/Documents/git/live $ python3 volume.py
Traceback (most recent call last):
  File "/Users/mac/Documents/git/live/volume.py", line 5, in <module>
    set.scan(scan_devices=True, scan_clip_names=True)
  File "/usr/local/lib/python3.9/site-packages/pylive-0.2.1-py3.9.egg/live/set.py", line 642, in scan
  File "/usr/local/lib/python3.9/site-packages/pylive-0.2.1-py3.9.egg/live/set.py", line 326, in num_tracks
  File "/usr/local/lib/python3.9/site-packages/pylive-0.2.1-py3.9.egg/live/query.py", line 240, in query
live.exceptions.LiveConnectionError: Timed out waiting for response from LiveOSC. Is Live running and LiveOSC installed?
$ ~/Documents/git/live $
```

Ports don't respond:

```
nc -v localhost 9000
nc -v localhost 9001
nc -v mylocalip 9000
nc -v mylocalip 9001
```

Settings:
![Screenshot 2022-02-07 at 00 44 37](https://user-images.githubusercontent.com/15680538/152704692-770ca96b-ff47-40a1-a1fa-79dd512de3c1.png)

**Comment by laimison** [comment]
It started to work the next day. Haven't done any change apart restarting apps and Mac.
