### ISSUE TITLE
detailed install instructions?

### ISSUE THREAD

**Issue by hems** [ideoforms/pylive#3]
Hello, 

I followed your link to LiveOSC and i got it working on AL9.

I checked my python version and it says: ````2.7.11````

I installed pyOSC by running: ````pip install pyOSC````

I also installed the package "live" by running: ````pip install live````

When on the examples folder, i try to run an example, for instance:
````
cd examples
python ex-device-randomise.py
````
but then i get an error:
````
Traceback (most recent call last):
  File "ex-device-randomise.py", line 9, in <module>
    import live
ImportError: No module named live
````

if i move the file one level up and execute
````
mv ex-device-randomise.py ..
cd ..
python ex-device-randomise.py
````
 i get a different error:
````
Traceback (most recent call last):
  File "ex-device-randomise.py", line 9, in <module>
    import live
  File "/Users/h/Desktop/--projects/serum/pylive/live/__init__.py", line 35, in <module>
    from set import *
  File "/Users/h/Desktop/--projects/serum/pylive/live/set.py", line 1, in <module>
    import live.query
  File "/Users/h/Desktop/--projects/serum/pylive/live/query.py", line 6, in <module>
    import liblo
ImportError: No module named liblo
````

By now i'm not sure how to install liblo and also why after installing the package "live" i can't just run my script from the "examples" folder - it seens python isn't finding the files after pip install has run ?

I must be doing something wrong regarding installing the libraries using pip or running multiple versions of python on my OSX ?

Would really appreciate some help here!

Thank you

**Comment by hems** [comment]
There are two things i had to do to fix the issue:

1 - install pyliblo "manually" on my OSX, by download source and then: ````sh ./configure.sh;make;make install````

2 - running ````pip install pylive```` instead of ````pip install live````

now my scripts seems to work from anywhere (( :
