### ISSUE TITLE
Non-ASCII character '\xe2' in file live/set.py on line 810

### ISSUE THREAD

**Issue by styk-tv** [ideoforms/pylive#6]
On Mojave
On Live 10.0.6

LiveOsc
```
commit 0c849b7c45efedf48f0f64b844b82e6734d11ae3 (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel Jones <daniel@jones.org.uk>
Date:   Sun May 26 18:16:50 2019 +0100

    Update README
```

PyLive
```
commit 4b845258ca8fa1121e4e81ee7baeda5bec0740e8 (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel Jones <daniel@jones.org.uk>
Date:   Sun May 26 18:18:14 2019 +0100

    Update README
```

Install of above version based on commit id:
```
polfilm@mac7:~/git_neux/pylive$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to pylive.egg-info/requires.txt
writing pylive.egg-info/PKG-INFO
writing top-level names to pylive.egg-info/top_level.txt
writing dependency_links to pylive.egg-info/dependency_links.txt
reading manifest file 'pylive.egg-info/SOURCES.txt'
writing manifest file 'pylive.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.14-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.14-x86_64/egg
creating build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/query.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/object.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/device.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/track.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/constants.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/__init__.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/scene.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/group.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/exceptions.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/clip.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/set.py -> build/bdist.macosx-10.14-x86_64/egg/live
copying build/lib/live/parameter.py -> build/bdist.macosx-10.14-x86_64/egg/live
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/query.py to query.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/object.py to object.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/device.py to device.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/track.py to track.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/constants.py to constants.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/scene.py to scene.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/group.py to group.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/exceptions.py to exceptions.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/clip.py to clip.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/set.py to set.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/live/parameter.py to parameter.pyc
creating build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying pylive.egg-info/PKG-INFO -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying pylive.egg-info/SOURCES.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying pylive.egg-info/dependency_links.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying pylive.egg-info/requires.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying pylive.egg-info/top_level.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pylive-0.1.5-py2.7.egg' and adding 'build/bdist.macosx-10.14-x86_64/egg' to it
removing 'build/bdist.macosx-10.14-x86_64/egg' (and everything under it)
Processing pylive-0.1.5-py2.7.egg
Copying pylive-0.1.5-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding pylive 0.1.5 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/pylive-0.1.5-py2.7.egg
Processing dependencies for pylive==0.1.5
Searching for pyliblo==0.10.0
Best match: pyliblo 0.10.0
Processing pyliblo-0.10.0-py2.7-macosx-10.14-x86_64.egg
pyliblo 0.10.0 is already the active version in easy-install.pth
Installing send_osc script to /usr/local/bin
Installing dump_osc script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages/pyliblo-0.10.0-py2.7-macosx-10.14-x86_64.egg
Finished processing dependencies for pylive==0.1.5


polfilm@mac7:~/git_neux/pylive$ python
Python 2.7.16 (default, Apr 12 2019, 15:32:40)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import live
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "live/__init__.py", line 35, in <module>
    from .set import *
  File "live/set.py", line 810
SyntaxError: Non-ASCII character '\xe2' in file live/set.py on line 810, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

install of 0.1.4 from pypi works but gives me index out of range on tracks scan.  Any hints?

**Comment by styk-tv** [comment]
i've added `# -*- coding: utf-8 -*-` at the top of set.py file to move things forward. i now see the following:

```
>>> import request
>>> import live
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "live/__init__.py", line 35, in <module>
    from .set import *
  File "live/set.py", line 16, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request
```

I think i'm chasing a red herring. I will try this with python3.

**Comment by styk-tv** [comment]
Uff. Much better:

```
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import live
>>> set = live.Set()
>>> set.scan(scan_clip_names = True, scan_devices = True)
>>> track = set.tracks[0]
>>> print("Track name %s" % track.name)
Track name 1-MIDI
>>> track = set.tracks[1]
>>> print("Track name %s" % track.name)
Track name 2-MIDI
>>>
```

a lot better than 2.7 but still not at 100%

```
================================================== test session starts ===================================================
platform darwin -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.11.0 -- /usr/local/opt/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /Users/polfilm/git_neux/pylive, inifile: setup.cfg
collected 37 items

tests/test_set.py::test_set_connected PASSED                                                                       [  2%]
tests/test_set.py::test_set_tempo[127.5] PASSED                                                                    [  5%]
tests/test_set.py::test_set_tempo[80] PASSED                                                                       [  8%]
tests/test_set.py::test_set_tempo[200] PASSED                                                                      [ 10%]
tests/test_set.py::test_set_quantization[0] PASSED                                                                 [ 13%]
tests/test_set.py::test_set_quantization[1] PASSED                                                                 [ 16%]
tests/test_set.py::test_set_quantization[2] PASSED                                                                 [ 18%]
tests/test_set.py::test_set_quantization[3] PASSED                                                                 [ 21%]
tests/test_set.py::test_set_quantization[4] PASSED                                                                 [ 24%]
tests/test_set.py::test_set_quantization[5] PASSED                                                                 [ 27%]
tests/test_set.py::test_set_quantization[6] PASSED                                                                 [ 29%]
tests/test_set.py::test_set_quantization[7] PASSED                                                                 [ 32%]
tests/test_set.py::test_set_quantization[8] PASSED                                                                 [ 35%]
tests/test_set.py::test_set_quantization[9] PASSED                                                                 [ 37%]
tests/test_set.py::test_set_quantization[10] PASSED                                                                [ 40%]
tests/test_set.py::test_set_quantization[11] PASSED                                                                [ 43%]
tests/test_set.py::test_set_quantization[12] PASSED                                                                [ 45%]
tests/test_set.py::test_set_quantization[13] PASSED                                                                [ 48%]
tests/test_set.py::test_set_time[0.0] PASSED                                                                       [ 51%]
tests/test_set.py::test_set_time[1.0] PASSED                                                                       [ 54%]
tests/test_set.py::test_set_time[2.5] PASSED                                                                       [ 56%]
tests/test_set.py::test_set_play PASSED                                                                            [ 59%]
tests/test_set.py::test_set_stop PASSED                                                                            [ 62%]
tests/test_set.py::test_set_num_tracks FAILED                                                                      [ 64%]
tests/test_set.py::test_set_num_scenes PASSED                                                                      [ 67%]
tests/test_set.py::test_get_master_volume PASSED                                                                   [ 70%]
tests/test_set.py::test_set_master_volume PASSED                                                                   [ 72%]
tests/test_set.py::test_get_master_pan PASSED                                                                      [ 75%]
tests/test_set.py::test_set_master_pan PASSED                                                                      [ 78%]
tests/test_set.py::test_set_scan FAILED                                                                            [ 81%]
tests/test_set.py::test_set_load PASSED                                                                            [ 83%]
tests/test_set.py::test_set_save FAILED                                                                            [ 86%]
tests/test_set.py::test_set_get_track_named FAILED                                                                 [ 89%]
tests/test_set.py::test_set_get_group_named PASSED                                                                 [ 91%]
tests/test_set.py::test_set_wait_for_next_beat PASSED                                                              [ 94%]
tests/test_track.py::test_track_get_clips PASSED                                                                   [ 97%]
tests/test_track.py::test_track_arm PASSED                                                                         [100%]

======================================================== FAILURES ========================================================
__________________________________________________ test_set_num_tracks ___________________________________________________

    def test_set_num_tracks():
        set = live.Set()
>       assert set.num_tracks == 6
E       assert 4 == 6
E         -4
E         +6

tests/test_set.py:76: AssertionError
_____________________________________________________ test_set_scan ______________________________________________________

    def test_set_scan():
        set = live.Set()
        assert set.scanned == False
        assert len(set.tracks) == 0
        set.scan()
        assert set.scanned == True
>       assert len(set.tracks) == 6
E       assert 4 == 6
E         -4
E         +6

tests/test_set.py:106: AssertionError
_____________________________________________________ test_set_save ______________________________________________________

    def test_set_save():
        set = live.Set()

        set.save(LIVE_TMP_SET_NAME)
        set.load(LIVE_TMP_SET_NAME)
        assert len(set.tracks) == 0

        set.scan()
>       assert len(set.tracks) == 6
E       assert 4 == 6
E         -4
E         +6

tests/test_set.py:144: AssertionError
________________________________________________ test_set_get_track_named ________________________________________________

    def test_set_get_track_named():
        set = live.Set()
>       set.scan()

tests/test_set.py:153:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
live/set.py:731: in scan
    scene_count = self.num_scenes
live/set.py:314: in num_scenes
    return self.live.query("/live/scenes")[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <live.query.Query object at 0x10d2a0f28>, msg = '/live/scenes', args = (), kwargs = {}
response_address = '/live/scenes', timeout = 5, rv = False

    def query(self, msg, *args, **kwargs):
    	""" Send a Live command and synchronously wait for its response:

    		return live.query("/live/tempo")

    	Returns a list of values. """

    	#------------------------------------------------------------------------
    	# Use **kwargs because we want to be able to specify an optional kw
    	# arg after variable-length args --
    	# eg live.query("/set/freq", 440, 1.0, response_address = "/verify/freq")
    	#
    	# http://stackoverflow.com/questions/5940180/python-default-keyword-arguments-after-variable-length-positional-arguments
    	#------------------------------------------------------------------------

    	#------------------------------------------------------------------------
    	# Some calls produce responses at different addresses
    	# (eg /live/device -> /live/deviceall). Specify a response_address to
    	# take account of this.
    	#------------------------------------------------------------------------
    	response_address = kwargs.get("response_address", None)
    	if response_address:
    		response_address = response_address
    	else:
    		response_address = msg

    	#------------------------------------------------------------------------
    	# Create an Event to block the thread until this response has been
    	# triggered.
    	#------------------------------------------------------------------------
    	self.osc_server_events[response_address] = threading.Event()

    	#------------------------------------------------------------------------
    	# query_rv will be populated by the callback, storing the return value
    	# of the OSC query.
    	#------------------------------------------------------------------------
    	self.query_address = response_address
    	self.query_rv = []
    	self.cmd(msg, *args)

    	#------------------------------------------------------------------------
    	# Wait for a response.
    	#------------------------------------------------------------------------
    	timeout = kwargs.get("timeout", self.osc_timeout)
    	rv = self.osc_server_events[response_address].wait(timeout)

    	if not rv:
>   		raise LiveConnectionError("Timed out waiting for response from LiveOSC. Is Live running and LiveOSC installed?")
E     live.exceptions.LiveConnectionError: Timed out waiting for response from LiveOSC. Is Live running and LiveOSC installed?

live/query.py:140: LiveConnectionError
==================================================== warnings summary ====================================================
.eggs/pytest-4.5.0-py3.7.egg/_pytest/mark/structures.py:324
  /Users/polfilm/git_neux/pylive/.eggs/pytest-4.5.0-py3.7.egg/_pytest/mark/structures.py:324: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================================== 4 failed, 33 passed, 1 warnings in 14.83 seconds ====================================
```

**Comment by styk-tv** [comment]
<img width="583" alt="Screenshot 2019-05-27 at 01 46 28" src="https://user-images.githubusercontent.com/838921/58389354-c80bbf80-8021-11e9-9daf-bb9ab3b9378f.png">

Test result set. I guess safe to say requirement of 2.6+ should be bumped up. Above passed with 3.7.3.

**Comment by ideoforms** [comment]
Many thanks for the report and analysis. I've incorporated the fixes you've mentioned above, which means it should now be Python 2.7 compatible again (although I may still increase the min required version to Python 3 in the near future).
